# Nombre visible en la pestaña Actions
name: Build & Push to Docker Hub (multi-arch)

on:
# Se ejecuta solo cuando hay un push a la rama main
# Define cuándo se ejecuta el workflow.
  push:
    branches: ["main"]

jobs: # Un workflow se compone de jobs (tareas)
  build-push:
    runs-on: ubuntu-latest # GitHub usa un runner con Ubuntu / GitHub usa un servidor temporal con Ubuntu para correr los pasos.
    env:
# Nombre base de la imagen en Docker Hub (se arma con el usuario del Secret)
# Define variables que usarán los pasos siguientes
      IMAGE_NAME: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/demo-django-devops2

    steps:
# Paso 1: bajar el código del repo al runner
      - name: Checkout
        uses: actions/checkout@v4

# Paso 2: login en Docker Hub con usuario y token almacenados en Secrets
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

# Paso 3: habilitar QEMU para compilar imágenes para distintas arquitecturas
# Instala QEMU → permite construir imágenes para arquitecturas diferentes (ej: arm64 para Mac M1/M2 y amd64 para PCs normales)
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3 #emulación para construir arm64/amd64

# Paso 4: inicializar Docker Buildx (builder avanzado)
# Configura Docker Buildx, un builder avanzado que soporta multi-arch y caché compartido.
      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

# Paso 5: construir y publicar la imagen en Docker Hub
      - name: Build & Push (amd64 + arm64)
        uses: docker/build-push-action@v6
        with:
          context: . # usar el código actual como contexto
          push: true # empujar la imagen al registry
          platforms: linux/amd64,linux/arm64 #multi-arch
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ github.sha }}
          cache-from: type=gha # usar cache para acelerar
          cache-to: type=gha,mode=max
